CREATE TABLE IF NOT EXISTS polls (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id varchar NOT NULL UNIQUE,
  admin_token varchar NOT NULL UNIQUE,
  title varchar NOT NULL,
  description text,
  creator_name text,
  creator_email text NOT NULL,
  is_anonymous boolean NOT NULL DEFAULT true,
  allow_multiple_votes boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at timestamptz
);

CREATE TABLE IF NOT EXISTS poll_options (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  poll_id integer NOT NULL REFERENCES polls(id) ON DELETE CASCADE,
  option_text varchar NOT NULL,
  position integer NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS votes (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  poll_id integer NOT NULL REFERENCES polls(id) ON DELETE CASCADE,
  option_id integer NOT NULL REFERENCES poll_options(id) ON DELETE CASCADE,
  voter_name varchar,
  voter_token varchar,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
