CREATE TABLE IF NOT EXISTS poll_participations (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  poll_id integer NOT NULL REFERENCES polls(id) ON DELETE CASCADE,
  voter_token_hash text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (poll_id, voter_token_hash)
);
