ALTER TABLE polls
  ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'active',
  ADD COLUMN IF NOT EXISTS activation_token varchar UNIQUE,
  ADD COLUMN IF NOT EXISTS activated_at timestamptz DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS blocked_at timestamptz,
  ADD COLUMN IF NOT EXISTS blocked_reason text,
  ADD COLUMN IF NOT EXISTS creator_ip inet,
  ADD COLUMN IF NOT EXISTS creator_ip_expires_at timestamptz;

UPDATE polls
SET creator_ip_expires_at = COALESCE(creator_ip_expires_at, created_at + interval '1 year')
WHERE creator_ip IS NOT NULL;

CREATE TABLE IF NOT EXISTS poll_reports (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  poll_id integer NOT NULL REFERENCES polls(id) ON DELETE CASCADE,
  reporter_email text NOT NULL,
  reason text NOT NULL,
  details text,
  reporter_ip inet,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resolved_at timestamptz
);

CREATE INDEX IF NOT EXISTS idx_polls_status_created_at
  ON polls(status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_poll_reports_poll_id_created_at
  ON poll_reports(poll_id, created_at DESC);
