CREATE TABLE IF NOT EXISTS ignored_creator_emails (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text NOT NULL UNIQUE,
  reason text,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_ignored_creator_emails_created_at
  ON ignored_creator_emails(created_at DESC);
