CREATE TABLE IF NOT EXISTS rate_limit_events (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action text NOT NULL,
  rate_key text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_rate_limit_events_action_key_created_at
  ON rate_limit_events(action, rate_key, created_at DESC);
