CREATE TABLE IF NOT EXISTS poll_questions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  poll_id integer NOT NULL REFERENCES polls(id) ON DELETE CASCADE,
  question_text text NOT NULL,
  question_type text NOT NULL DEFAULT 'single_choice',
  allow_multiple_votes boolean NOT NULL DEFAULT false,
  position integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT poll_questions_question_type_check
    CHECK (question_type IN ('single_choice')),
  CONSTRAINT poll_questions_position_check
    CHECK (position >= 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_poll_questions_poll_id_position
  ON poll_questions(poll_id, position);

CREATE INDEX IF NOT EXISTS idx_poll_questions_poll_id
  ON poll_questions(poll_id);

INSERT INTO poll_questions (
  poll_id,
  question_text,
  question_type,
  allow_multiple_votes,
  position,
  created_at
)
SELECT
  p.id,
  p.title,
  'single_choice',
  p.allow_multiple_votes,
  0,
  p.created_at
FROM polls p
WHERE NOT EXISTS (
  SELECT 1
  FROM poll_questions pq
  WHERE pq.poll_id = p.id
    AND pq.position = 0
);

ALTER TABLE poll_options
  ADD COLUMN IF NOT EXISTS question_id integer;

UPDATE poll_options po
SET question_id = pq.id
FROM poll_questions pq
WHERE po.question_id IS NULL
  AND pq.poll_id = po.poll_id
  AND pq.position = 0;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM poll_options
    WHERE question_id IS NULL
  ) THEN
    RAISE EXCEPTION 'poll_options.question_id konnte nicht fuer alle bestehenden Optionen gesetzt werden.';
  END IF;
END $$;

ALTER TABLE poll_options
  ALTER COLUMN question_id SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.table_constraints
    WHERE table_schema = current_schema()
      AND table_name = 'poll_options'
      AND constraint_name = 'poll_options_question_id_fkey'
  ) THEN
    ALTER TABLE poll_options
      ADD CONSTRAINT poll_options_question_id_fkey
      FOREIGN KEY (question_id)
      REFERENCES poll_questions(id)
      ON DELETE CASCADE;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_poll_options_question_id_position
  ON poll_options(question_id, position);
